// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("tes1", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("tes1", async function () {
    await driver.get("https://webskrining.bpjs-kesehatan.go.id/skrining");
    await driver.manage().window().setRect({ width: 866, height: 1025 });
    await driver.findElement(By.id("nik_txt")).click();
    await driver.findElement(By.id("nik_txt")).sendKeys("0000910424496");
    await driver.findElement(By.id("TglLahir_src")).click();
    await driver.findElement(By.id("TglLahir_src")).sendKeys("28-11-2004");
    await driver.findElement(By.css(".has-feedback > label")).click();
    await driver.findElement(By.id("captchaCode_txt")).click();
    await driver.findElement(By.id("nik_txt")).click();
    await driver.findElement(By.id("nik_txt")).sendKeys("0000910424496");
    await driver.findElement(By.id("TglLahir_src")).click();
    await driver.findElement(By.id("TglLahir_src")).sendKeys("28-11-2004");
    await driver.findElement(By.id("AppCaptcha_CaptchaImageDiv")).click();
    await driver.findElement(By.id("captchaCode_txt")).click();
    await driver.findElement(By.id("captchaCode_txt")).sendKeys("H9e6x");
    await driver.findElement(By.id("btnCariPetugas")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("beratBadan_txt")).click();
    await driver.findElement(By.id("beratBadan_txt")).sendKeys("60");
    await driver.findElement(By.id("tinggiBadan_txt")).sendKeys("160");
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider3A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1B > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider3G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider3J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider1J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider3K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider7K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider8K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider9K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider3L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider1L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("hasilSkrJudul_Top")).click();
    await driver.findElement(By.id("hasilSkrining_NoJKN")).click();
    await driver.findElement(By.id("btnBacktoHome1")).click();
    await driver.findElement(By.id("nik_txt")).click();
    await driver.findElement(By.id("nik_txt")).sendKeys("0000910424496");
    await driver.findElement(By.id("TglLahir_src")).click();
    await driver.findElement(By.css("#frmPilihPst > .survey-wrapper")).click();
    await driver.findElement(By.id("TglLahir_src")).sendKeys("28-11-2004");
    await driver.findElement(By.id("captchaCode_txt")).click();
    await driver.findElement(By.id("captchaCode_txt")).sendKeys("hvTrh");
    await driver.findElement(By.id("btnCariPetugas")).click();
    await driver.findElement(By.id("btnCariPetugas")).click();
    {
      const element = await driver.findElement(By.id("btnCariPetugas"));
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    await driver.findElement(By.id("btnBacktoHome1")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("beratBadan_txt")).click();
    await driver.findElement(By.id("beratBadan_txt")).sendKeys("60");
    await driver.findElement(By.id("tinggiBadan_txt")).sendKeys("160");
    await driver.findElement(By.id("nohp_txt")).click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider3A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6A > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1B > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider3G > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider3J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider1J > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider3K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider7K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider8K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider9K > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver
      .findElement(
        By.css("#slider1L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider2L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider3L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider6L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider4L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver
      .findElement(
        By.css("#slider5L > .answer-item:nth-child(2) > .answertext")
      )
      .click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("nextGenBtn")).click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.close();
  });
});
